"""Symmetry group: signed permutations of coordinates (B_m, automorphisms of the complex commuting with the antipode)
times signed permutations of label magnitudes.  An element is g = (pi, eps, lpi, leps):
    vertex  v -> w with w[k] = eps[k] * v[pi[k]]
    label   l -> leps[|l|] * sign(l) * lpi[|l|]
Averaging over a subgroup is valid over F_2 only if its order is odd; use `z3z3_generators` / `assert_odd_order`.
"""
import itertools


def identity(m, mags):
    return (tuple(range(m)), (1,) * m, {a: a for a in mags}, {a: 1 for a in mags})


def act_vertex(g, v):
    pi, eps, _, _ = g
    return tuple(eps[k] * v[pi[k]] for k in range(len(v)))


def act_label(g, l):
    _, _, lpi, leps = g
    return leps[abs(l)] * (1 if l > 0 else -1) * lpi[abs(l)]


def act(cx, g, alpha):
    """Image of a partial labeling alpha (tuple of (free index, label)) — result sorted by free index."""
    out = []
    for i, l in alpha:
        j, s = cx.rep(act_vertex(g, cx.free[i]))
        out.append((j, s * act_label(g, l)))
    return tuple(sorted(out))


def compose(g, h):
    """(g o h): first h then g."""
    pig, epsg, lpig, lepsg = g
    pih, epsh, lpih, lepsh = h
    m = len(pig)
    pi = tuple(pih[pig[k]] for k in range(m))
    eps = tuple(epsg[k] * epsh[pig[k]] for k in range(m))
    lpi = {a: lpig[lpih[a]] for a in lpih}
    leps = {a: lepsh[a] * lepsg[lpih[a]] for a in lpih}
    return (pi, eps, lpi, leps)


def _key(g):
    pi, eps, lpi, leps = g
    return (pi, eps, tuple(sorted(lpi.items())), tuple(sorted(leps.items())))


def generated_group(gens, m, mags):
    """All elements of the subgroup generated by gens (closure by composition)."""
    e = identity(m, mags)
    seen = {_key(e): e}
    stack = [e]
    while stack:
        x = stack.pop()
        for g in gens:
            y = compose(g, x)
            k = _key(y)
            if k not in seen:
                seen[k] = y
                stack.append(y)
    return list(seen.values())


def assert_odd_order(gens, m, mags):
    order = len(generated_group(gens, m, mags))
    if order % 2 == 0:
        raise ValueError(f"subgroup has even order {order}: averaging is not valid over F_2")
    return order


def full_group(m, mags):
    G = []
    for pi in itertools.permutations(range(m)):
        for eps in itertools.product([1, -1], repeat=m):
            for lpi in itertools.permutations(mags):
                for leps in itertools.product([1, -1], repeat=len(mags)):
                    G.append((pi, eps, dict(zip(mags, lpi)), dict(zip(mags, leps))))
    return G


def _coord_perm(m, mags, pi):
    return (tuple(pi), (1,) * m, {a: a for a in mags}, {a: 1 for a in mags})


def _coord_flip(m, mags, k):
    return (tuple(range(m)), tuple(-1 if i == k else 1 for i in range(m)), {a: a for a in mags}, {a: 1 for a in mags})


def _mag_perm(m, mags, lpi):
    return (tuple(range(m)), (1,) * m, dict(lpi), {a: 1 for a in mags})


def _mag_flip(m, mags, a0):
    return (tuple(range(m)), (1,) * m, {a: a for a in mags}, {a: -1 if a == a0 else 1 for a in mags})


def label_group_generators(m, mags):
    """Signed permutations of magnitudes (order |mags|! 2^|mags|, even)."""
    gens = []
    if len(mags) >= 2:
        for a, b in zip(mags, mags[1:]):
            lpi = {c: c for c in mags}
            lpi[a], lpi[b] = b, a
            gens.append(_mag_perm(m, mags, lpi))
    gens.append(_mag_flip(m, mags, mags[0]))
    return gens


def coordinate_group_generators(m, mags, coords=None):
    """Signed permutations of the given coordinates (default all): adjacent transpositions and one sign flip."""
    coords = list(range(m)) if coords is None else list(coords)
    gens = []
    for a, b in zip(coords, coords[1:]):
        pi = list(range(m))
        pi[a], pi[b] = b, a
        gens.append(_coord_perm(m, mags, pi))
    gens.append(_coord_flip(m, mags, coords[0]))
    return gens


def full_group_generators(m, mags):
    return coordinate_group_generators(m, mags) + label_group_generators(m, mags)


def hemisphere_stabilizer_generators(m, mags):
    """Stabilizer of the hemisphere {x_m != -1}: signed permutations of coordinates 0..m-2, times the label group."""
    return coordinate_group_generators(m, mags, range(m - 1)) + label_group_generators(m, mags)


def coordinate_cycle(m, mags, coords=(0, 1, 2)):
    """The cycle coords[0] -> coords[1] -> ... on coordinates (as a permutation of positions)."""
    pi = list(range(m))
    for a, b in zip(coords, coords[1:] + coords[:1]):
        pi[a] = b
    return _coord_perm(m, mags, pi)


def magnitude_cycle(m, mags, cyc=None):
    cyc = tuple(mags[:3]) if cyc is None else tuple(cyc)
    lpi = {a: a for a in mags}
    for a, b in zip(cyc, cyc[1:] + cyc[:1]):
        lpi[a] = b
    return _mag_perm(m, mags, lpi)


def z3z3_generators(m, mags):
    """Z_3 x Z_3: a 3-cycle on coordinates 0,1,2 and a 3-cycle on the first three magnitudes (odd order 9).
    With fewer than 3 magnitudes only the coordinate Z_3 is available (order 3)."""
    gens = [coordinate_cycle(m, mags)]
    if len(mags) >= 3:
        gens.append(magnitude_cycle(m, mags))
    return gens


def orbits(items, gens, act_fn):
    """Partition `items` (an iterable, e.g. of partial labelings) into orbits under the group generated by gens.
    Returns (orb: item -> orbit id, members: list of member lists).  Items reached from an item but not in `items`
    are included (the caller must pass a gens-invariant set for this to be meaningful)."""
    orb = {}
    members = []
    for a in items:
        if a in orb:
            continue
        oid = len(members)
        orb[a] = oid
        mem = [a]
        stack = [a]
        while stack:
            b = stack.pop()
            for g in gens:
                c = act_fn(g, b)
                if c not in orb:
                    orb[c] = oid
                    mem.append(c)
                    stack.append(c)
        members.append(mem)
    return orb, members
